### ISSUE TITLE
启动报错，已安装nonebot-plugin-htmlrender

### ISSUE THREAD

**Issue by YingLing3** [CCYellowStar/zhenxun_plugin_slave_market#12]
08-03 11:02:28 [ERROR] nonebot | Failed to import "nonebot_plugin_htmlrender"
Traceback (most recent call last):
  File "/home/bot/zhenxun_bot-main/bot.py", line 19, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 50, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 146, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bot/zhenxun_bot-main/extensive_plugin/zhenxun_plugin_slave_market/__init__.py", line 21, in <module>
    require("nonebot_plugin_htmlrender")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 179, in require
    plugin = load_plugin(name)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 155, in load_plugin
    raise RuntimeError(
RuntimeError: Module nonebot_plugin_htmlrender is not loaded as a plugin! Make sure not to import it before loading.
08-03 11:02:28 [ERROR] nonebot | Failed to import "zhenxun_plugin_slave_market"
Traceback (most recent call last):
  File "/home/bot/zhenxun_bot-main/bot.py", line 19, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 50, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 146, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bot/zhenxun_bot-main/extensive_plugin/zhenxun_plugin_slave_market/__init__.py", line 21, in <module>
    require("nonebot_plugin_htmlrender")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UCLvrwct-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 183, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_htmlrender"!

![image](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/44056856/399e09c4-c44f-4d86-a303-c080642fded6)

**Comment by CCYellowStar** [comment]
这个是插件加载问题，很玄学的问题

**Comment by CCYellowStar** [comment]
好像是不能把这个[nonebot-plugin-htmlrender]当成插件加载，他只是个依赖
