### ISSUE TITLE
群友退群导致 群友市场 命令 不工作

### ISSUE THREAD

**Issue by imxianyu21** [CCYellowStar/zhenxun_plugin_slave_market#13]
08-03 15:40:50 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.zhenxun_plugin_slave_market) failed.
Traceback (most recent call last):                                                                File "bot.py", line 21, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot--vfVceMT-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/zx/zhenxun_bot-main/extensive_plugin/zhenxun_plugin_slave_market/__init__.py", line 69, in _
    msg += f"|<img width='20%' src='http://q1.qlogo.cn/g?b=qq&nk={qq}&s=100'/>  {user_name}|{qq}|{p}|<img width='20%' src='http://q1.qlogo.cn/g?b=qq&nk={usern.user_id}&s=100'/>  {umaster}|\n"
AttributeError: 'NoneType' object has no attribute 'user_id'

**Comment by imxianyu21** [comment]
![Cache_6ecd8db058e00893~3](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/110275302/fe97d66f-ae1e-47f7-b9c4-69d0a75f17f2)
第二个是已退出群的群友，发现已退群的群友数据没有被删除

**Comment by CCYellowStar** [comment]
我更新了但还没发布release

**Comment by imxianyu21** [comment]
> 
我扒下仓库看看（）

**Comment by CCYellowStar** [comment]
> > 
> 
> 我扒下仓库看看（）

但是这个只能检测退群，没开机器人的时候退了他也不知道

**Comment by imxianyu21** [comment]
> > > 
> > 
> > 
> > 我扒下仓库看看（）
> 
> 但是这个只能检测退群，没开机器人的时候退了他也不知道

那就手动血洗数据库（）

**Comment by CCYellowStar** [comment]
更新了
